openapi: 3.0.0
components:
  schemas:
    GetProducts:
      type: array
      items:
        type: object
        properties:
          count:
            type: number
          description:
            type: string
          id:
            type: string
          price:
            type: number
          title:
            type: string
    Product:
      type: object
      properties:
        count:
          type: number
        description:
          type: string
        id:
          type: string
        price:
          type: number
        title:
          type: string
    NotFoundError:
      type: object
      properties:
        message:
          type: string
  securitySchemes: {}
info:
  title: My API
  description: This is my API
  version: '1'
paths:
  '/products/{id}':
    get:
      operationId: getProductById
      summary: Get Product By ID
      responses:
        '200':
          description: Status 200 Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Status 404 Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
  /products:
    get:
      operationId: getProducts
      summary: Get Products
      responses:
        '200':
          description: Status 200 Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetProducts'
